### PR TITLE
Move package to the global namespace

### PR DESCRIPTION
**Pull request by m1guelpf**

### CODE REVIEW

**Comment by OwenMelbz** [comment]
Good idea, I was thinking about this the other day. Do you think we'll need to change the physical php namespace in them? Or will it be okay with auto discovery??

**Comment by m1guelpf** [comment]
@OwenMelbz I think we should also change the PHP namespace, but to finish this, we need https://github.com/laravel-frontend-presets/zurb-foundation/issues/1.

**Comment by OwenMelbz** [comment]
@m1guelpf Thats cool, are we waiting on @Laraveldeep for that?

**Comment by m1guelpf** [comment]
@OwenMelbz Yes, we need to be able to upload packages to packagist under the namespace before changing.

**Comment by m1guelpf** [comment]
@OwenMelbz We now have access over the packagist namespace. We can continue

**Comment by OwenMelbz** [comment]
@m1guelpf Have merged and updated the rest of the namespaces!

**Pull request merged**
